@ComprasVentas_HostAddress = http://localhost:5136

GET {{ComprasVentas_HostAddress}}/weatherforecast/
Accept: application/json

### MAS SERVICIOS

POST  {{ComprasVentas_HostAddress}}/roles
Accept: application/json

###

# Permiso Controller Tests

### Get All Permisos
GET {{ComprasVentas_HostAddress}}/api/Permiso
Accept: application/json

### Create Permiso
POST {{ComprasVentas_HostAddress}}/api/Permiso
Content-Type: application/json

{
  "nombre": "Crear Usuario",
  "recurso": "Usuario",
  "accion": "Crear"
}

###

# Rol Controller Tests

### Get All Roles
GET {{ComprasVentas_HostAddress}}/api/Rol
Accept: application/json

### Get Rol by Id
GET {{ComprasVentas_HostAddress}}/api/Rol/100
Accept: application/json

### Create Rol
POST {{ComprasVentas_HostAddress}}/api/Rol
Content-Type: application/json

{
  "nombre": "Administrador",
  "descripcion": "Rol con permisos administrativos",
  "permisoIds": [1, 2]
}

### Update Rol
PUT {{ComprasVentas_HostAddress}}/api/Rol/1
Content-Type: application/json

{
  "nombre": "Administrador Actualizado",
  "descripcion": "Rol actualizado",
  "permisoIds": [1, 2, 3]
}

### Delete Rol
DELETE {{ComprasVentas_HostAddress}}/api/Rol/1
Accept: application/json

### Get Usuario by Id
GET {{ComprasVentas_HostAddress}}/api/Usuario/dsadsad
Accept: application/json

###

# Usuario Controller Tests

### Get All Usuarios
GET {{ComprasVentas_HostAddress}}/api/Usuario
Accept: application/json

### Create Usuario
POST {{ComprasVentas_HostAddress}}/api/Usuario
Content-Type: application/json

{
  "nombre": "usuario1",
  "correo": "usuario1@example.com",
  "password": "Passwor1!",
  "nombres": "Juan",
  "apellidos": "Perez",
  "fechaNacimiento": "01-01-1990",
  "genero": "Masculino",
  "telefono": "123456789",
  "direccion": "Calle 123",
  "nacionalidad": "Mexicano",
  "rolIds": [1]
}

### Update Usuario
PUT {{ComprasVentas_HostAddress}}/api/Usuario/1
Content-Type: application/json

{
  "nombre": "usuario1_updated",
  "correo": "usuario1_updated@example.com",
  "password": "Password2!",
  "nombres": "Juan",
  "apellidos": "Perez",
  "fechaNacimiento": "01/01/1990",
  "genero": "Masculino",
  "telefono": "123456789",
  "direccion": "Calle 123",
  "nacionalidad": "Mexicano",
  "rolIds": [1, 2]
}

### Delete Usuario
DELETE {{ComprasVentas_HostAddress}}/api/Usuario/1
Accept: application/json
